# Написать функцию, решающую систему линейных уравнений с трёх диагональной матрицей методом Гаусса. Протестировать на случайной матрице размера N = 20

In [71]:
import numpy as np
from random import randint

In [106]:
N=int(input())
x = []
b = np.zeros(N)

for i in range(N):
    b[i]=float(randint(1,5))
a=np.zeros((N,N))
for i in range(N):
    a[i,i]=float(randint(1,5))
    if i!=0:
        a[i,i-1]=float(randint(1,5))
    if i!=N-1:
        a[i,i+1]=float(randint(1,5))
print("Исходная матрица")
print(a)
print("Исходные ответы")
print(b)
for i in range(1,N):
    if a[i-1,i-1]!=0:
        k=a[i,i-1]/a[i-1,i-1]
        a[i]-=(a[i-1]*k)
        b[i]=b[i]-b[i-1]*k
    else:
        a[i],a[i-1]=a[i-1],a[i].copy()
        b[i],b[i-1]=b[i-1],b[i].copy()
print("Новая матрица")        
print(a)
print("Cтрочка ответов для проверки")
print(b)
x.append(b[len(a) -  1]/a[len(a)-1][len(a)-1])
for i in range(len(a) - 1, 0, -1):
    x.append((b[i-1] - a[i-1][i]*x[N-i-1])/a[i-1][i-1])
x = x[::-1]



10
Исходная матрица
[[2. 5. 0. 0. 0. 0. 0. 0. 0. 0.]
 [2. 3. 3. 0. 0. 0. 0. 0. 0. 0.]
 [0. 4. 5. 3. 0. 0. 0. 0. 0. 0.]
 [0. 0. 4. 4. 3. 0. 0. 0. 0. 0.]
 [0. 0. 0. 5. 2. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 5. 3. 0. 0. 0.]
 [0. 0. 0. 0. 0. 5. 4. 5. 0. 0.]
 [0. 0. 0. 0. 0. 0. 1. 2. 5. 0.]
 [0. 0. 0. 0. 0. 0. 0. 5. 1. 4.]
 [0. 0. 0. 0. 0. 0. 0. 0. 4. 5.]]
Исходные ответы
[3. 4. 2. 1. 4. 2. 5. 2. 4. 2.]
Новая матрица
[[ 2.00000000e+00  5.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00 -2.00000000e+00  3.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.10000000e+01  3.00000000e+00
   0.00000000e+00  0.00000000e+00  0.00000000e+00  0.00000000e+00
   0.00000000e+00  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  2.90909091e+00
   3.00000000e+00  0

In [107]:
print(" Вторая строчка ответов для проверки")
for i in range(N):
    s=0
    for j in range(N):
        s+=(x[j]*a[i,j]) 
    
    print(s, end=' ')

 Вторая строчка ответов для проверки
3.0 1.0 4.0 -0.4545454545454546 4.78125 3.5148514851485144 1.6945996275605215 0.5624012638230649 5.254404510218464 0.2704708884249597 